[project]
name = "darkknot"
version = "0.1.0"
description = "Flex-Knot reconstruction of dark energy w(a), for use with Cobaya"
authors = [{name="Adam Neil Ormondroyd", email="Adam.Ormondroyd@gmail.com"}]
readme = "README.md"
dependencies = ["numpy", "cobaya", "linf@git+ssh://github.com/Ormorod/linf@main"]

[project.urls]
repository = "https://github.com/Ormorod/darkknot"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project.optional-dependencies]
dev = ["black"]
